version: '3.8'

services:
  backend:
    image: backend_image:latest
    deploy:
      replicas: 1
    ports:
      - "5000:5000"
    networks:
      - backend-network

networks:
  backend-network:
    driver: overlay
