version: '3.9'

networks:
  nothing:
    external: true
    driver: overlay
services:
  backend:
    image: backend_image:latest
    deploy:
      replicas: 1
    ports:
      - "8000:8000"
    volumes:
      - ../backend/src/logs:/app/src/logs
    networks:
      - nothing
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_PORT=3306
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=administrator_db

