version: '3.9'

services:
  backend:
    image: backend_image:latest
    deploy:
      replicas: 1
    ports:
      - "5000:5000"
    networks:
      - nothing
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=example
      - DATABASE_NAME=mydatabase

networks:
  nothing:
    external: true