version: '3.8'

services:
  database:
    image: mariadb:latest
    deploy:
      replicas: 1
    ports:
      - "3306:3306"
    networks:
      - database-network
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=administrator_db

networks:
  backend-network:
    driver: overlay
