version: '3.9'

networks:
  nothing:
    external: true
    driver: overlay

services:
  database:
    image: database_image:latest
    deploy:
      replicas: 1
    networks:
      - nothing
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=administrator_db