version: '3.9'

networks:
  nothing:
    external: true


services:
  database:
    image: database_image:latest
    deploy:
      replicas: 1
    ports:
      - "3306:3306"
    networks:
      - nothing
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=administrator_db