version: '3.8'

services:
  database:
    image: mariadb:latest
    deploy:
      replicas: 1
    ports:
      - "3306:5001"
    networks:
      - somenetwork
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=administrator_db