version: '3.9'

services:
  frontend:
    image: frontend_image:latest
    deploy:
      replicas: 1
    ports:
      - "8000:8000"
    networks:
      - nothing
    environment:
      - BACKEND_URL=http://backend:5000
