version: '3.9'

networks:
  nothing:
    external: true
  frontend-network:
    driver: overlay

services:
  frontend:
    image: frontend_image:latest
    deploy:
      replicas: 1
    ports:
      - "5000:5000"
    networks:
      - nothing
      - frontend-network
    environment:
      - BACKEND_URL=http://backend:8000
