version: '3.9'

services:
  frontend:
    image: frontend_image:latest
    deploy:
      replicas: 1
    ports:
      - "8000:8000"
    networks:
      - frontend-network
    environment:
      - BACKEND_URL=http://backend:5000

networks:
  frontend-network:
    driver: overlay