version: '3.8'

services:
  frontend:
    image: frontend_image:latest
    deploy:
      replicas: 1
    ports:
      - "8000:8000"
    networks:
      - somenetwork
    environment:
      - BACKEND_URL=http://backend:5000

networks:
  somenetwork:
    driver: overlay